import type { Metadata } from "next";

import { geistSans, geistMono, lato, rubik } from "@/lib/fonts";

import "@/styles/globals.css";
import { ThemeProvider } from "@/components/custom/theme-provider";

export const metadata: Metadata = {
  title: "Nuno Fernandes | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={rubik.variable}>
      <body className={`${rubik.className} antialiased overflow-x-hidden`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* ----- background fixed ----- */}
          <div className="fixed inset-0 -z-10 h-full w-full items-center px-5 py-24 [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)]"></div>

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
